### ISSUE TITLE
ibus_sensor does not work on NANO

### ISSUE THREAD

**Issue by Dmitrykrz** [bmellink/IBusBM#18]
This example works fine with arduino mega.
I want to run it on nano. So I change 
` // initialize serial port for debug`
 ` Serial.begin(115200);`
`  // iBUS connected to serial1`
`  IBus.begin(Serial1);`
to 
` // initialize serial port for debug`
`  //Serial.begin(115200);`
`  // iBUS connected to serial`
 ` IBus.begin(Serial);`
Usb cable is not connected.
In this case it does not work. I see no sensors on the transmitter. 
Is nano supported for sensor only operation?

**Comment by id3vi5er** [comment]
It works with a nano, i use it myself  you just need to Programm ist via
the 6 Pin header and a ISP, in my case a Myavrlight (: then the tx/rx works
just fine, but not in combination with I2C or other hardware timing related
things, I suppose...

Dmitrykrz <notifications@github.com> schrieb am Mo., 9. Nov. 2020, 13:11:

**Comment by id3vi5er** [comment]
And you cannot run the Serial and the iBus on the same port, doesn't work either...
Just get the Serial.begin() out of the code and it should work....

**Comment by Dmitrykrz** [comment]
> Just get the Serial.begin() out of the code and it should work....
This is exactly what I did, look at my code.
Why I need to program it via ISP? To get rid of arduino bootloader?
