### ISSUE TITLE
Faster update

### ISSUE THREAD

**Issue by jan5650** [bmellink/IBusBM#19]
Dear bmellink!

You did great job with this Ibus library!
I used it in a project, where i need to watch the sensors. Sadly the sensors value update "slow", once per a sec. 
Can i modify it to update more faster?

Can you help me what i need to modify in the IbusBM.cpp or in the IbusBM.h file?
It wil be great if the sensores update twice in a sec

Thank you!

**Comment by bmellink** [comment]
Hi Jan

The problem of updating the sensor frequency/speed is not the library, but relates to your receiver or a receiver setting. 

Let me explain: The receiver polls each sensor one after each other. After polling all known sensors, the receiver may wait a while and then starts polling again. The library simply responds to the polling signals. This means - the more sensors you have the longer the polling loop may take. The library has an internal counter `cnt_sensor` you can print on a console that will increment each time the receiver is polling a sensor. If you have only one sensor, this counter can be used to figure out which update frequency your receiver uses.

However, to my knowledge, there is no way to influence the receiver polling cycle frequency. It is possible different ibus receivers use different cycle times and maybe there is a parameter you can change. I have not yet looked at that. If you find anything, please let me know and I will add that info to the readme file.
