### ISSUE TITLE
Generic STM32F103C8T6 Compile error

### ISSUE THREAD

**Issue by 1371030** [bmellink/IBusBM#5]
警告： IBusBM 库要求运行在 avr, esp32, stm32 架构()，可能与你现在运行在 STM32F1 架构上的开发板()不兼容。
/Users/admin/Documents/Arduino/libraries/IBusBM/src/IBusBM.cpp:38:15: error: variable or field 'onTimer' declared void
 void  onTimer(stimer_t *htim) {

"IBusBM.h" 对应多个库
 已使用： /Users/admin/Documents/Arduino/libraries/IBusBM
exit status 1
为开发板 Generic STM32F103C series 编译时出错。

**Comment by bmellink** [comment]
Using Google translate I think you are saying: Warning: The IBusBM library is required to run on avr, esp32, stm32 architecture (), which may not be compatible with the development board () you are running on the STM32F1 architecture.
And then: Error compiling for development board Generic STM32F103C series.
I did not test the lib on STM32. Thtat part of the code was created by another user. If you find the fix, please let me know

**Comment by bmellink** [comment]
closed
